### ISSUE TITLE
Error when using multiprocessing

### ISSUE THREAD

**Issue by yumy-yumy** [ShichenXie/scorecardpy#24]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/miniconda3/envs/mlflow-323f7dfca0660eb56720b79b6e1754559df603e4/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/miniconda3/envs/mlflow-323f7dfca0660eb56720b79b6e1754559df603e4/lib/python3.6/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/miniconda3/envs/mlflow-323f7dfca0660eb56720b79b6e1754559df603e4/lib/python3.6/site-packages/scorecardpy-0.1.7-py3.6.egg/scorecardpy/woebin.py", line 702, in woebin2
    stop_limit=stop_limit, max_num_bin=max_num_bin, breaks=breaks, spl_val=spl_val)
  File "/miniconda3/envs/mlflow-323f7dfca0660eb56720b79b6e1754559df603e4/lib/python3.6/site-packages/scorecardpy-0.1.7-py3.6.egg/scorecardpy/woebin.py", line 495, in woebin2_tree
    if binning_tree is None: binning_tree = initial_binning
UnboundLocalError: local variable 'binning_tree' referenced before assignment
"""

**Comment by sunrisehang** [comment]
Windows jupter cannot use multithreading.
linux can.

**Comment by yumy-yumy** [comment]
I was running by Pycharm in MacOS.
